### PR TITLE
Hidden input text

### PR DESCRIPTION
**Pull request by brenopolanski**
screenshot from 2015-12-03 15 16 01

### CODE REVIEW

**Comment by wesbos** [comment]
If you hide it, the copy to clipboard stops working. Did you check that? I haven't looked into it enough to for a fix

**Comment by brenopolanski** [comment]
Hey @wesbos. I am lying. I added opacity for zero. The "clipboard" this working ;)

**Comment by brenopolanski** [comment]
and other thing... I added text alignment in cursors.

screenshot from 2015-12-03 15 28 00

**Comment by wesbos** [comment]
Perfect - than you!

**Pull request merged**
